# Generated by Django 5.2.1 on 2025-05-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_set_doctor_emails'),
        ('authentication', '0003_create_admin_log_table'),
    ]

    operations = [
    ]
